import { Geist, Geist_Mono,Inter } from "next/font/google";
import "./globals.css";
import Topbar from "../components/Topbar";
import Sidebar from "../components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}  ${inter.variable} antialiased`}
      >
        <div className='bg-[#EAEAEA]'>
       <div className="flex h-screen overflow-hidden ">
          
        
            <Sidebar/>
         

         
          <div className="flex-1 flex flex-col min-w-0 min-h-0  ">
           
            <div className=''>
              <Topbar />
            </div>

         
            <main className="flex-1 min-h-0 overflow-y-auto hide-scrollbar  pt-6 pb-[50px] pl-6 pr-12 ">
            <div className="w-full max-w-full overflow-x-hidden bg-red-200 ">
            {children}
            </div>
          </main>


          </div>
        </div>
    </div>
      </body>
    </html>
  );
}
